# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d7936378c2aff173d0164e2c9c27ff303022575f04d480b5ad17878e5b3611643e66d92a3784508093e3f83abafbe1239b48d9c92ecc983d5b7b257d6f8ddaa

test:
  secret_key_base: 6253907c5f6aab6c7a25e82b54da06e7bddb6b39c630872361a27349aaa93b6d0098bb4ca3b72123f2d98bddef33102e02719ac6be4e934f21e802bb2e1dbcfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
